-- Authentication was introduced after the baseline users table. Hibernate
-- validates this column at startup, so it must be created by Flyway rather
-- than generated by JPA.
ALTER TABLE users
    ADD COLUMN password_hash VARCHAR(255);

-- Existing environments created before authentication cannot log in until a
-- password-reset flow is available. New registrations always populate this
-- column through AuthService.
